# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icann < Formula
  desc "ICANN MOSAPI and RRI CLI"
  homepage "https://github.com/onasunnymorning/icann-client"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.1.2/icann-client_v0.1.2_darwin_amd64.tar.gz"
      sha256 "1d73434319de429c97672a0ee75bf339610c02e4701909eb154b982baa0ef210"

      def install
        bin.install "icann"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.1.2/icann-client_v0.1.2_darwin_arm64.tar.gz"
      sha256 "41121debe9beec05470e43b651e8835ce8f529e66c67b45bb1016cdd449cc6a4"

      def install
        bin.install "icann"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.1.2/icann-client_v0.1.2_linux_amd64.tar.gz"
      sha256 "3bd036cee8aa09b26a0a698a1c256f1a2bc6db7b5f7eb8f5983a8d2766c7508d"
      def install
        bin.install "icann"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.1.2/icann-client_v0.1.2_linux_arm64.tar.gz"
      sha256 "138c49364213272e68e662d6490f05600b0990be29d782461d105ae1ade0e790"
      def install
        bin.install "icann"
      end
    end
  end

  test do
    system "#{bin}/icann", "--help"
  end
end
