# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icann < Formula
  desc "ICANN MOSAPI and RRI CLI"
  homepage "https://github.com/onasunnymorning/icann-client"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.2.0/icann-client_v0.2.0_darwin_amd64.tar.gz"
      sha256 "54167e8a98982d88f94aa2d8e8cecb73ac5ebe89b09cce09ab34a0c6d0e2383d"

      def install
        bin.install "icann"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.2.0/icann-client_v0.2.0_darwin_arm64.tar.gz"
      sha256 "16a02648352b1126028757c640b25f987dba8c1263d709981ecc9b704cb4106e"

      def install
        bin.install "icann"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.2.0/icann-client_v0.2.0_linux_amd64.tar.gz"
      sha256 "d5b56be201c019896d9cad90313c289cd9faa4453704c1aba1dc66125fd69c65"
      def install
        bin.install "icann"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.2.0/icann-client_v0.2.0_linux_arm64.tar.gz"
      sha256 "778bc4aa3c16850a1da4e866bf7403753b11d4df62c91075942721cd6dd3a762"
      def install
        bin.install "icann"
      end
    end
  end

  test do
    system "#{bin}/icann", "--help"
  end
end
