# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epp < Formula
  desc "EPP command-line tool"
  homepage "https://github.com/onasunnymorning/eppclient"
  version "1.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.2/eppclient_1.3.2_darwin_amd64.tar.gz"
      sha256 "641335e64d95f1c9d9e25f7913fba1e19ce1b02b19c71a92e37b2aec27346111"

      define_method(:install) do
        bin.install "epp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.2/eppclient_1.3.2_darwin_arm64.tar.gz"
      sha256 "ecba23309ebd6af1b4aa92a39dbd427ad2eb5fbdc92336ca1070ed989d7d4fa8"

      define_method(:install) do
        bin.install "epp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.2/eppclient_1.3.2_linux_amd64.tar.gz"
      sha256 "16f395e535a919da48980cd0946a4243a742287e96bdaab8cc853c1733de5d76"
      define_method(:install) do
        bin.install "epp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.2/eppclient_1.3.2_linux_arm64.tar.gz"
      sha256 "d965afcaf74fb4439c59061e7491091a80f2b4e3cbdeb90f137b81d6b460980f"
      define_method(:install) do
        bin.install "epp"
      end
    end
  end
end
