# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epp < Formula
  desc "EPP command-line tool"
  homepage "https://github.com/onasunnymorning/eppclient"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.0/eppclient_1.3.0_darwin_amd64.tar.gz"
      sha256 "0790fe746ea9f169baee560178a7f5f4561545c0cf4670a22289abd0066e95de"

      define_method(:install) do
        bin.install "epp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.0/eppclient_1.3.0_darwin_arm64.tar.gz"
      sha256 "ac09f31fd7c282d47a89fa1ee9aee972d124a6f7c804e6f16b750ae4f62bcdc4"

      define_method(:install) do
        bin.install "epp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.0/eppclient_1.3.0_linux_amd64.tar.gz"
      sha256 "94b3eab214bc8d16ff4b82f5897aad6d0c9f86d1e3eccf9ba4540b0dcdc144cb"
      define_method(:install) do
        bin.install "epp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.3.0/eppclient_1.3.0_linux_arm64.tar.gz"
      sha256 "5b8de35036c7d2160512cf928e948795460992292f0eb6f04feaf3e76a2f36e0"
      define_method(:install) do
        bin.install "epp"
      end
    end
  end
end
