# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epp < Formula
  desc "EPP command-line tool"
  homepage "https://github.com/onasunnymorning/eppclient"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.0.0/eppclient_1.0.0_darwin_amd64.tar.gz"
      sha256 "ece28a8583bf488acf1baaf5d73341236e1b4c26db3c89685dc45c62f5e3eb3b"

      def install
        bin.install "epp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.0.0/eppclient_1.0.0_darwin_arm64.tar.gz"
      sha256 "5555bf32774fb11203cf6ad18c311dd9a2ed9d83d905026e071d0caa29a91ea2"

      def install
        bin.install "epp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.0.0/eppclient_1.0.0_linux_amd64.tar.gz"
      sha256 "2bc3c362869623cabc124266e4707c601d13350d0dcc0596ffbba1f188d20038"
      def install
        bin.install "epp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/eppclient/releases/download/v1.0.0/eppclient_1.0.0_linux_arm64.tar.gz"
      sha256 "340b9e098c2b971b07ee37a7d7224962f64444105792d6f91134557e302b6d01"
      def install
        bin.install "epp"
      end
    end
  end
end
