# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icann < Formula
  desc "ICANN MOSAPI and RRI CLI"
  homepage "https://github.com/onasunnymorning/icann-client"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.3.0/icann-client_v0.3.0_darwin_amd64.tar.gz"
      sha256 "f2046fa0b299ae726186b1f143b7c258f5ecd9e4b2efbda6efc4386f3159c1af"

      def install
        bin.install "icann"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.3.0/icann-client_v0.3.0_darwin_arm64.tar.gz"
      sha256 "d49708baf0e9d258011ba41e6fccdffc40331a1fbfd211f9f4c805846e5ac776"

      def install
        bin.install "icann"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.3.0/icann-client_v0.3.0_linux_amd64.tar.gz"
      sha256 "42b62b87d7744c32b168cd722a7828f8e3305af180fda40a5a75c6440efbc1d3"
      def install
        bin.install "icann"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/icann-client/releases/download/v0.3.0/icann-client_v0.3.0_linux_arm64.tar.gz"
      sha256 "c933921b9b6773367d4bc48a6c20dfe3863085ba38e6b497cb3184a05502cea5"
      def install
        bin.install "icann"
      end
    end
  end

  test do
    system "#{bin}/icann", "--help"
  end
end
