# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PremiumListMaker < Formula
  desc "Tool for managing domain label lists and generating premium pricing"
  homepage "https://github.com/onasunnymorning/premium-list-maker"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.5/premium-list-maker_0.0.5_darwin_amd64.tar.gz"
      sha256 "c318f01d0b20cfc3e0fda92acde0cd2134a706c39de840113d085c7d3f2ca4a5"

      def install
        bin.install "premium-list-maker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.5/premium-list-maker_0.0.5_darwin_arm64.tar.gz"
      sha256 "4dfff1ce5aeaae1af2b39d1533de19bc9f18c33efb730977efff457e033b8a43"

      def install
        bin.install "premium-list-maker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.5/premium-list-maker_0.0.5_linux_amd64.tar.gz"
      sha256 "019dadeb40be56b042bb136d9d7d1c3f96ec2c509f168509b07ea9fb8dbf2df3"
      def install
        bin.install "premium-list-maker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.5/premium-list-maker_0.0.5_linux_arm64.tar.gz"
      sha256 "f1bd3170033cb9366ca6157cdb7cec63c920a1a7cce79969cb0d78b1504a9ea6"
      def install
        bin.install "premium-list-maker"
      end
    end
  end
end
