# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PremiumListMaker < Formula
  desc "Tool for managing domain label lists and generating premium pricing"
  homepage "https://github.com/onasunnymorning/premium-list-maker"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.4/premium-list-maker_0.0.4_darwin_amd64.tar.gz"
      sha256 "4a606cdc35cec489ca555e94c474da00a105d03af7dfcb9f64cd8e9c33571cfc"

      def install
        bin.install "premium-list-maker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.4/premium-list-maker_0.0.4_darwin_arm64.tar.gz"
      sha256 "43b191f39d508d8745a4dcbfb04714ba90e2fb20f1472a13f70ce58735efb985"

      def install
        bin.install "premium-list-maker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.4/premium-list-maker_0.0.4_linux_amd64.tar.gz"
      sha256 "da781220a7b842f5d9754d19236ed630abd018f7cb3cfc3719978eb0e53ea2fc"
      def install
        bin.install "premium-list-maker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onasunnymorning/premium-list-maker/releases/download/v0.0.4/premium-list-maker_0.0.4_linux_arm64.tar.gz"
      sha256 "7aa958b224eef2bd6c6ec359e74acfbea9edcc47e85caa292a5ed7d647a78d31"
      def install
        bin.install "premium-list-maker"
      end
    end
  end
end
